build: off

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

cache:
  - node_modules

branches:
  only:
    - master

platform:
  - x64

environment:
  NVS_VERSION: 1.4.2
  matrix:
    - NODEJS_VERSION: node/4
    - NODEJS_VERSION: node/6
    - NODEJS_VERSION: node/8
    - NODEJS_VERSION: node/10
    - NODEJS_VERSION: nightly
    - NODEJS_VERSION: rc
    - NODEJS_VERSION: canary
    - NODEJS_VERSION: chakracore
    - NODEJS_VERSION: chakracore-nightly

matrix:
  allow_failures:
    - NODEJS_VERSION: nightly
    - NODEJS_VERSION: canary
    - NODEJS_VERSION: chakracore
    - NODEJS_VERSION: chakracore-nightly

install:
  - git clone --branch v%NVS_VERSION% --depth 1 https://github.com/jasongin/nvs %LOCALAPPDATA%\nvs
  - set PATH=%LOCALAPPDATA%\nvs;%PATH%
  - nvs --version

  - nvs remote rc https://nodejs.org/download/rc/
  - nvs remote canary https://nodejs.org/download/v8-canary/

  - nvs add %NODEJS_VERSION%/%PLATFORM%
  - nvs use %NODEJS_VERSION%/%PLATFORM%
  - node --version
  - node -p process.arch
  - npm --version

  - npm install -g --production windows-build-tools
  - npm install

test_script:
  - npm run build
